Server:
  RunMode: debug
  HttpPort: 8080
  ReadTimeout: 60
  WriteTimeout: 60
App:
  DefaultPageSize: 10
  MaxPageSize: 100
  LogSavePath: storage/logs
  LogFileName: app
  LogFileExt: .log
  UploadSavePath: storage/uploads
  UploadServerUrl: http://127.0.0.1:8080/static
  UploadImageMaxSize: 5  # MB
  UploadImageAllowExts:
    - .jpg
    - .jpeg
    - .png
Database:
  DBType: mysql
  Username: root
  Password: root
  Host: 127.0.0.1
  Port: 3306
  DBName: blog_service
  TablePrefix: blog_
  Charset: utf8
  Parsetime: true
  MaxIdleConns: 10
  MaxOpenConns: 30
JWT:
  Secret: eason
  Issuer: blog-service
  Expire: 7200
Email:
  Host: smtp.qq.com
  Port: 465
  UserName: xxxx@qq.com
  Password: xxxxxxxx
  IsSSL: true
  From: xxxx@qq.com
  To:
    - xxxx1@qq.com
    - xxxx2@qq.com